print '\n'.join(["Hello World"])
print '\n'.join(["Hello World, Again"])
print '\n'.join(["Three"])
print '\n'.join(["Four"])
print '\n'.join(["Five"])
print '\n'.join(["Legen...", "wait for it", "...dary!!"])
print '\n'.join(["It's going to be legen--", "wait for it", "--and I hope you're not lactose intolerant, because the second half of the word is--", "dairy!!"])
print '\n'.join(["you guys are ridiculous"])